sonar.projectKey=HealthApp
sonar.working.directory=C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\310508\\source\\repos\\HAP_Pod3
sonar.pullrequest.cache.basepath=C:\\Users\\310508\\source\\repos\\HAP_Pod3
sonar.sources=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.vs\\VSWorkspaceState.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.vs\\HAP_Pod3.slnx\\v18\\DocumentLayout.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.vs\\HealthAxis.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.vs\\HealthAxis.slnx\\v18\\DocumentLayout.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\dotnet-tools.json"

8C89BC6A-C8F5-4CBA-8532-CD1256E62637.sonar.projectKey=HealthApp:8C89BC6A-C8F5-4CBA-8532-CD1256E62637
8C89BC6A-C8F5-4CBA-8532-CD1256E62637.sonar.projectName=HealthApp
8C89BC6A-C8F5-4CBA-8532-CD1256E62637.sonar.projectBaseDir=C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp
8C89BC6A-C8F5-4CBA-8532-CD1256E62637.sonar.sourceEncoding=utf-8
8C89BC6A-C8F5-4CBA-8532-CD1256E62637.sonar.sources=
8C89BC6A-C8F5-4CBA-8532-CD1256E62637.sonar.tests=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Databases\\AppointmentDb.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Databases\\DoctorDb.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Databases\\HealthRecordDb.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Databases\\PatientDb.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\AppointmentConflictException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\AppointmentNotFoundException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\DoctorAlreadyExistsException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\DoctorNotFoundException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\DoctorUnavailableException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\HealthRecordExistsException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\HealthRecordNotFoundException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\PastDateException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\PatientNotFoundException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\SpecialisationNotFoundException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Exceptions\\UserExitException.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Helpers\\InputValidator.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Helpers\\SlotHelper.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Interfaces\\IAppointmentRepository.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Interfaces\\IAppointmentService.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Interfaces\\IDoctorRepository.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Interfaces\\IDoctorService.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Interfaces\\IHealthRecordRepository.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Interfaces\\IHealthRecordService.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Interfaces\\IPatientRepository.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Interfaces\\IPatientService.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Menus\\AppointmentMenu.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Menus\\DoctorMenu.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Menus\\HealthRecordMenu.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Menus\\PatientMenu.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Models\\Appointment.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Models\\AppointmentStatus.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Models\\Doctor.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Models\\Gender.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Models\\HealthRecord.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Models\\Patient.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Repositories\\AppointmentRepository.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Repositories\\DoctorRepository.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Repositories\\HealthRecordRepository.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Repositories\\PatientRepository.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Services\\AppointmentService.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Services\\DoctorService.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Services\\HealthRecordService.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\ConsoleApp\\Services\\PatientService.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\Program.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\coverage.xml",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\obj\\HealthApp.csproj.nuget.dgspec.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\obj\\project.assets.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\bin\\Debug\\net10.0\\HealthApp.deps.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\bin\\Debug\\net10.0\\HealthApp.runtimeconfig.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp\\obj\\Debug\\net10.0\\HealthApp.sourcelink.json"

8C89BC6A-C8F5-4CBA-8532-CD1256E62637.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\0"
8C89BC6A-C8F5-4CBA-8532-CD1256E62637.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\0\\Issues.json"
8C89BC6A-C8F5-4CBA-8532-CD1256E62637.sonar.cs.scanner.telemetry=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\0\\Telemetry.json"

8C89BC6A-C8F5-4CBA-8532-CD1256E62637.sonar.working.directory=C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\.sonar\\mod0
12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3.sonar.projectKey=HealthApp:12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3
12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3.sonar.projectName=HealthApp
12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3.sonar.projectBaseDir=C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp
12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3.sonar.sourceEncoding=utf-8
12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3.sonar.sources=
12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3.sonar.tests=\


12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\1"
12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\1\\Issues.json"
12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3.sonar.cs.scanner.telemetry=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\1\\Telemetry.json"

12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3.sonar.working.directory=C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\.sonar\\mod1
993DE0E5-FEF7-453E-BF89-10B6F8B90F14.sonar.projectKey=HealthApp:993DE0E5-FEF7-453E-BF89-10B6F8B90F14
993DE0E5-FEF7-453E-BF89-10B6F8B90F14.sonar.projectName=HealthApp.Tests
993DE0E5-FEF7-453E-BF89-10B6F8B90F14.sonar.projectBaseDir=C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests
993DE0E5-FEF7-453E-BF89-10B6F8B90F14.sonar.sourceEncoding=utf-8
993DE0E5-FEF7-453E-BF89-10B6F8B90F14.sonar.sources=
993DE0E5-FEF7-453E-BF89-10B6F8B90F14.sonar.tests=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\obj\\HealthApp.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\obj\\project.assets.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\bin\\Debug\\net10.0\\HealthApp.deps.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\bin\\Debug\\net10.0\\HealthApp.runtimeconfig.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\bin\\Debug\\net10.0\\HealthApp.Tests.deps.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\bin\\Debug\\net10.0\\HealthApp.Tests.runtimeconfig.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\obj\\Debug\\net10.0\\HealthApp.Tests.sourcelink.json",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\Repositories\\AppointmentRepositoryTests.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\Repositories\\DoctorRepositoryTests.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\Repositories\\HealthRecordRepositoryTests.cs",\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\HealthApp.Tests\\Repositories\\PatientRepositoryTests.cs"

993DE0E5-FEF7-453E-BF89-10B6F8B90F14.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\2"
993DE0E5-FEF7-453E-BF89-10B6F8B90F14.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\2\\Issues.json"
993DE0E5-FEF7-453E-BF89-10B6F8B90F14.sonar.cs.scanner.telemetry=\
"C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\2\\Telemetry.json"

993DE0E5-FEF7-453E-BF89-10B6F8B90F14.sonar.working.directory=C:\\Users\\310508\\source\\repos\\HAP_Pod3\\.sonarqube\\out\\.sonar\\mod2
sonar.coverage.exclusions=**/Interfaces/**,**/Helpers/**,**/Databases/**,**/Menus/**,**/Models/**,**/Exceptions/**
sonar.host.url=http://localhost:9000
sonar.cs.vscoveragexml.reportsPaths=coverage.xml
sonar.exclusions=coverage.xml
sonar.visualstudio.enable=false

sonar.modules=8C89BC6A-C8F5-4CBA-8532-CD1256E62637,12FFCF29-BBAE-48C2-933C-A9B3D3EDC4A3,993DE0E5-FEF7-453E-BF89-10B6F8B90F14

