sonar.projectKey=HealthApp
sonar.working.directory=C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\310466\\Desktop\\Learning\\HealthAxis
sonar.pullrequest.cache.basepath=C:\\Users\\310466\\Desktop\\Learning\\HealthAxis
sonar.sources=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.vs\\HealthAxis.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.vs\\HealthAxis.slnx\\v18\\DocumentLayout.json"

C50AE62B-DE73-49F2-AB8D-A7DA8275E86E.sonar.projectKey=HealthApp:C50AE62B-DE73-49F2-AB8D-A7DA8275E86E
C50AE62B-DE73-49F2-AB8D-A7DA8275E86E.sonar.projectName=HealthApp
C50AE62B-DE73-49F2-AB8D-A7DA8275E86E.sonar.projectBaseDir=C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp
C50AE62B-DE73-49F2-AB8D-A7DA8275E86E.sonar.sourceEncoding=utf-8
C50AE62B-DE73-49F2-AB8D-A7DA8275E86E.sonar.tests=
C50AE62B-DE73-49F2-AB8D-A7DA8275E86E.sonar.sources=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Databases\\AppointmentDb.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Databases\\DoctorDb.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Databases\\HealthRecordDB.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Databases\\PatientDb.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\AppointmentConflictException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\AppointmentNotCompletedException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\AppointmentNotFoundException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\DoctorAlreadyExistsException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\DoctorNotFoundException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\DoctorUnavailableException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\HealthRecordExistsException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\HealthRecordNotFoundException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\PastDateException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\PatientAlreadyExistsException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\PatientNotFoundException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Exceptions\\SpecialisationNotFoundException.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Helpers\\InputValidator.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Helpers\\SlotHelper.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Interfaces\\IAppointmentRepository.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Interfaces\\IAppointmentService.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Interfaces\\IDoctorRepository.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Interfaces\\IDoctorService.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Interfaces\\IHealthRecordRepository.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Interfaces\\IHealthRecordService.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Interfaces\\IPatientRepository.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Interfaces\\IPatientService.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Menus\\AppointmentMenu.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Menus\\DoctorMenu.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Menus\\HealthRecordMenu.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Menus\\PatientMenu.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Models\\Appointment.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Models\\AppointmentStatus.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Models\\Doctor.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Models\\HealthRecord.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Models\\Patient.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Repositories\\AppointmentRepository.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Repositories\\DoctorRepository.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Repositories\\HealthRecordRepository.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Repositories\\PatientRepository.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Services\\AppointmentService.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Services\\DoctorService.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Services\\HealthRecordService.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\ConsoleApp\\Services\\PatientService.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\Program.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\.vs\\VSWorkspaceState.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\obj\\HealhApp.csproj.nuget.dgspec.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\obj\\HealthApp.csproj.nuget.dgspec.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\obj\\project.assets.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\.vs\\HealthApp.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\.vs\\HealthApp.slnx\\v18\\DocumentLayout.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\bin\\Debug\\net10.0\\HealthApp.deps.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\bin\\Debug\\net10.0\\HealthApp.runtimeconfig.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\obj\\Debug\\net10.0\\HealhApp.sourcelink.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp\\obj\\Debug\\net10.0\\HealthApp.sourcelink.json"

C50AE62B-DE73-49F2-AB8D-A7DA8275E86E.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\0"
C50AE62B-DE73-49F2-AB8D-A7DA8275E86E.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\0\\Issues.json"
C50AE62B-DE73-49F2-AB8D-A7DA8275E86E.sonar.cs.scanner.telemetry=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\0\\Telemetry.json"

C50AE62B-DE73-49F2-AB8D-A7DA8275E86E.sonar.working.directory=C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\.sonar\\mod0
07846405-850F-47E8-AC1B-3B3D94F7850B.sonar.projectKey=HealthApp:07846405-850F-47E8-AC1B-3B3D94F7850B
07846405-850F-47E8-AC1B-3B3D94F7850B.sonar.projectName=HealthApp
07846405-850F-47E8-AC1B-3B3D94F7850B.sonar.projectBaseDir=C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp
07846405-850F-47E8-AC1B-3B3D94F7850B.sonar.sourceEncoding=utf-8
07846405-850F-47E8-AC1B-3B3D94F7850B.sonar.tests=
07846405-850F-47E8-AC1B-3B3D94F7850B.sonar.sources=\


07846405-850F-47E8-AC1B-3B3D94F7850B.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\1"
07846405-850F-47E8-AC1B-3B3D94F7850B.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\1\\Issues.json"
07846405-850F-47E8-AC1B-3B3D94F7850B.sonar.cs.scanner.telemetry=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\1\\Telemetry.json"

07846405-850F-47E8-AC1B-3B3D94F7850B.sonar.working.directory=C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\.sonar\\mod1
C0ABC8A6-F6BA-41F4-925F-86B5923C45EC.sonar.projectKey=HealthApp:C0ABC8A6-F6BA-41F4-925F-86B5923C45EC
C0ABC8A6-F6BA-41F4-925F-86B5923C45EC.sonar.projectName=HealthApp.Tests
C0ABC8A6-F6BA-41F4-925F-86B5923C45EC.sonar.projectBaseDir=C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests
C0ABC8A6-F6BA-41F4-925F-86B5923C45EC.sonar.sourceEncoding=utf-8
C0ABC8A6-F6BA-41F4-925F-86B5923C45EC.sonar.sources=
C0ABC8A6-F6BA-41F4-925F-86B5923C45EC.sonar.tests=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\obj\\HealthApp.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\obj\\project.assets.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\bin\\Debug\\net10.0\\HealthApp.deps.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\bin\\Debug\\net10.0\\HealthApp.runtimeconfig.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\bin\\Debug\\net10.0\\HealthApp.Tests.deps.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\bin\\Debug\\net10.0\\HealthApp.Tests.runtimeconfig.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\obj\\Debug\\net10.0\\HealthApp.Tests.sourcelink.json",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\Helpers\\InputValidatorTests.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\Repositories\\AppointmentRepositoryTests.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\Repositories\\DoctorRepositoryTests.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\Repositories\\HealthRecordRepositoryTests.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\Repositories\\PatientRepositoryTests.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\Services\\AppointmentServiceTests.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\Services\\DoctorServiceTests.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\Services\\HealthRecordServiceTests.cs",\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\HealthApp.Tests\\Services\\PatientServiceTests.cs"

C0ABC8A6-F6BA-41F4-925F-86B5923C45EC.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\2"
C0ABC8A6-F6BA-41F4-925F-86B5923C45EC.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\2\\Issues.json"
C0ABC8A6-F6BA-41F4-925F-86B5923C45EC.sonar.cs.scanner.telemetry=\
"C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\2\\Telemetry.json"

C0ABC8A6-F6BA-41F4-925F-86B5923C45EC.sonar.working.directory=C:\\Users\\310466\\Desktop\\Learning\\HealthAxis\\.sonarqube\\out\\.sonar\\mod2
sonar.coverage.exclusions=**/Interfaces/**,**/Helpers/**,**/Databases/**,**/Menus/**,**/Models/**,**/Exceptions/**,**/Program.cs
sonar.host.url=http://localhost:9000
sonar.cs.vscoveragexml.reportsPaths=coverage.xml
sonar.exclusions=coverage.xml
sonar.visualstudio.enable=false

sonar.modules=C50AE62B-DE73-49F2-AB8D-A7DA8275E86E,07846405-850F-47E8-AC1B-3B3D94F7850B,C0ABC8A6-F6BA-41F4-925F-86B5923C45EC

