pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        EB_APPLICATION_NAME = 'HealthCareApi'
        EB_ENVIRONMENT_NAME = 'HealthCareApi-dev'
        S3_BUCKET = 'health-bucket-748999353112-ap-south-1-an'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Clean previous build artifacts') {
            steps {
                bat 'if exist blazor-publish-temp rmdir /S /Q blazor-publish-temp'
                bat 'if exist publish rmdir /S /Q publish'
                bat 'if exist deploy-package.zip del /F /Q deploy-package.zip'

                bat 'if exist Health\\HealthCare.Api\\wwwroot\\blazor rmdir /S /Q Health\\HealthCare.Api\\wwwroot\\blazor'
            }
        }

        stage('Build Angular') {
            steps {
                dir('Health/HealthCareUser.Web') {
                    bat 'npm install'
                    bat 'npm run build'
                }
            }
        }

        stage('Publish Blazor') {
            steps {
                bat 'dotnet publish Health\\HealthCareAdmin.Web\\HealthCareAdmin.Web.csproj -c Release -o blazor-publish-temp'

                bat 'if not exist blazor-publish-temp\\wwwroot\\index.html (echo ERROR: index.html missing from Blazor publish output & exit /b 1)'
            }
        }

        stage('Copy Blazor into API wwwroot') {
            steps {
                bat 'if not exist Health\\HealthCare.Api\\wwwroot\\blazor mkdir Health\\HealthCare.Api\\wwwroot\\blazor'
                bat 'xcopy /E /Y /I blazor-publish-temp\\wwwroot\\* Health\\HealthCare.Api\\wwwroot\\blazor\\'

                bat 'if not exist Health\\HealthCare.Api\\wwwroot\\blazor\\index.html (echo ERROR: index.html missing after xcopy & exit /b 1)'
            }
        }

        stage('Publish API') {
            steps {
                bat 'dotnet publish Health\\HealthCare.Api\\HealthCare.Api.csproj -c Release -o publish'
            }
        }

        stage('Verify Package Contents') {
            steps {
                bat 'dir publish\\wwwroot\\blazor'

                bat 'if not exist publish\\wwwroot\\blazor\\index.html (echo ERROR: index.html missing from final publish output & exit /b 1)'
            }
        }

        stage('Zip published output') {
            steps {
                dir('publish') {
                    bat 'jar -cMf ../deploy-package.zip .'
                }
            }
        }

        stage('Upload to S3 and Deploy to EB') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'deploy-id'
                ]]) {

                    bat "aws s3 cp deploy-package.zip s3://%S3_BUCKET%/deploy-package-%BUILD_NUMBER%.zip --region %AWS_REGION%"

                    bat "aws elasticbeanstalk create-application-version --application-name %EB_APPLICATION_NAME% --version-label v-%BUILD_NUMBER% --source-bundle S3Bucket=%S3_BUCKET%,S3Key=deploy-package-%BUILD_NUMBER%.zip --region %AWS_REGION%"

                    bat "aws elasticbeanstalk update-environment --environment-name %EB_ENVIRONMENT_NAME% --version-label v-%BUILD_NUMBER% --region %AWS_REGION%"
                }
            }
        }
    }
}
