name: Validate Docker Build

on:
  push:
    branches: [Feature/Sprint5_Pod3_RijoBijuAbraham]
  pull_request:
    branches: [Feature/Sprint5_Pod3_RijoBijuAbraham]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Angular
        working-directory: HealthCare.Portal
        run: |
          npm ci
          npx ng build --configuration production

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Publish API
        run: dotnet publish HealthCare.Api/HealthCare.Api.csproj -c Release -o publish/api

      - name: Publish Blazor Admin
        run: dotnet publish HealthCare.Admin/HealthCare.Admin.csproj -c Release -o publish/admin

      - name: Update Blazor base href
        run: sed -i 's|<base href="/" />|<base href="/admin/" />|g' publish/admin/wwwroot/index.html

      - name: Build Docker image
        run: docker build -t healthcare-test .
